spring.application.name=orbit-backend
server.port=8080

# ─── MongoDB ───────────────────────────────────────────────────────────────────
spring.data.mongodb.uri=mongodb+srv://admin:Fz76KhKKwX0YoogZ@cluster0.swbbnvh.mongodb.net/orbit_db?appName=Cluster0

# ─── JWT ───────────────────────────────────────────────────────────────────────
app.jwt.secret=4b6f726269744f7262697453656372657450617373776f72644b657932303236!!
app.jwt.expiration=86400000

# ─── Google OAuth2 ─────────────────────────────────────────────────────────────
spring.security.oauth2.client.registration.google.client-id=459703089428-ej2idk301iec3ih881abc54scvm1otfj.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# ─── Frontend URL (used in OAuth2 redirect after Google login) ─────────────────
app.frontend.url=http://localhost:5173

# ─── CORS ──────────────────────────────────────────────────────────────────────
app.cors.allowed-origins=http://localhost:5173

# ─── File Upload ───────────────────────────────────────────────────────────────
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB
